DHI/modelskill

- fmskill/compare.py
- fmskill/model.py
- fmskill/plot.py
* Scatter ✔️ 
* Map ✔️ 
Skipping timeseries and histogram for now..
🚀 📦
> Refactored out plots

- fmskill/observation.py
- tests/test_pointobservation.py
> create PointObservation from dataframe

- .github/workflows/full_test.yml
- fmskill/compare.py
- fmskill/model.py
- fmskill/observation.py
- fmskill/utils.py
- setup.py
Let ModelResult output pd.DataFrame instead of mikeio.Dateset upon extraction as it will make it easier to use alternative formats (and create Comparer directly from DataFrames)
> Model result outputs dataframe

- fmskill/comparison.py
- fmskill/observation.py
- tests/test_modelresult.py
- tests/test_multimodelcompare.py
- tests/test_multivariable_compare.py
- tests/test_simple_compare.py
Rounding errors on DateTimeIndex have caused problems in fmskill. Related to https://github.com/DHI/mikeio/pull/206
> Fix time rounding errors

- docs/api.rst
- docs/getting_started.rst
- docs/index.rst
- docs/simple_compare.rst
- fmskill/comparison.py
- fmskill/connection.py
- tests/test_multimodelcompare.py
- tests/test_pointcompare.py
The connector is not yet properly documented. The purpose of this PR is to remove any reference to past ways of doing things and add documentation for the new ways.
> Improved connector documentation

- fmskill/comparison.py
- fmskill/connection.py
- tests/test_dmi_api.py
don't increase time interval for track data - may cause keyerror
> Fix bug in TrackComparer 

- docs/api.rst
- fmskill/metrics.py
- notebooks/Custom_metric.ipynb
Hit ratio is a metric that is easy to grasp, but requires a parameter, the acceptable deviation.
> Hit ratio metric

- fmskill/connection.py
- fmskill/model/__init__.py
- fmskill/model/abstract.py
- fmskill/model/dfs.py
- fmskill/model/factory.py
- fmskill/model/pandas.py
- fmskill/model/xarray.py
- fmskill/observation.py
- tests/test_model_pandas.py
- tests/test_modelresult.py
Until now it has not been possible to have track-type model results defined from a DataFrame as you can with dfs model results.
> Pandas track model result

- setup.py
[Installing Shapely](https://github.com/Toblerity/Shapely#installing-shapely) includes GEOS as is now simple to install.
> Include shapely as main dependency

- fmskill/data/altimetry.py
- tests/test_altimetry_api.py
> new columns in updated altimetry API

- fmskill/__init__.py
- fmskill/connection.py
- fmskill/metrics.py
- fmskill/model/factory.py
- fmskill/model/xarray.py
- setup.py
In some cases "import fmskill" takes too long time. This PR attempts to fix this.
> Improved load time

- fmskill/__init__.py
- fmskill/skill.py
- setup.py
replace deprecated style.set_precision with style.format
> Fix deprecation warning from pandas styler

- fmskill/observation.py
- tests/test_trackobservation.py
Use only default item it n_items=3, accept item as string, raise error if n_items<3
> TrackObservation item argument

- notebooks/Metrics_widget.ipynb
Notebook widget to demonstrate the different FMskill metrics
> Metrics widget

- README.md
- docs/api.rst
- fmskill/metrics.py
- notebooks/Metrics_widget.ipynb
- tests/test_metrics.py
max error and Willmott's Index of Agreement
> Add new metrics

- fmskill/model/abstract.py
Deafult in_domain should be True in base class
> fix failing in_domain validation for extraction from pandas modelresults

- docs/api.rst
- fmskill/metrics.py
add max_error to documentation
> add max_error to documentation

- fmskill/spatial.py
Fix bug when number of dimensions was larger than 1, as it entered a loop that it shouldn't
> Fix small plot bug in spatial.py

- fmskill/comparison.py
- fmskill/plot.py
A couple of changes:
* Changed QQ plot from Line to Markers
* Number of markers depends on size of data: 
If >3000 points, then 1000 markers (0.1% quantiles)
if >300 points, then 100 markers (1% quantiles)
else , 10 markers (10% quantiles). 
Default was 20 markers before (5% quantiles)
> Changes in QQ plot style

- fmskill/plot.py
Hi,
I added a grid to the scatter plot by default and changed the QQ markers from points to X, something like this
I have no further changes for the scatter plots (for the time being)
> added grid

- docs/api.rst
- fmskill/metrics.py
- tests/test_metrics.py
A metric commonly used in hydrology.
Rationale:
[Technical note: Inherent benchmark or not? Comparing Nash–Sutcliffe and Kling–Gupta efficiency scores](https://doi.org/10.5194/hess-23-4323-2019)
> Added metric Kling Gupta Efficiency

- fmskill/plot.py
- fmskill/styles/mood.yml
Hi, I made the following
* Some changed to the MOOD style in the mood .yml file
* I changed the grid from `:` and `grey`  to `black` and `line` but still with thickness 0.2.  Both the `:` + `grey` + `thin line` made it barely visible, now is still very thin but more clear to recognize
> minimal style changes

- fmskill/comparison.py
- notebooks/Track_comparison.ipynb
- notebooks/Track_comparison_global_waves.ipynb
- tests/test_comparer.py
- tests/test_comparercollection.py
wrapping xarray.Dataset.where() but defaulting to dropping nan. Also query method and new simplified (more unit, less integration) testing of Comparer and ComparerCollection.
> New Comparer method where()

- modelskill/comparison.py
- tests/test_comparer.py
Exporting comparer to dataframe now keeps aux columns and has better handling of dtypes
> Improved model to dataframe

- modelskill/comparison.py
> ComparerCollection deprecation warnings

- pyproject.toml
> Source dist without notebooks and tests

- modelskill/comparison/_comparer_plotter.py
- tests/test_comparer.py
> Q-Q plot for easy comparison across multiple models

- docs/api.rst
- docs/simple-compare.md
- modelskill/cli.py
- modelskill/settings.py
- modelskill/types.py
- tests/test_compare.py
- tests/test_connector_conf.py
A lot of the API documentation is currently missing - this PR adapts to the new API.
> Add missing api docs

- modelskill/__init__.py
- modelskill/configuration.py
- modelskill/connection.py
Part of decommissioning the Connector
> Move config to separate module

- modelskill/comparison/_collection.py
- modelskill/comparison/_collection_plotter.py
- modelskill/comparison/_comparer_plotter.py
- modelskill/comparison/_comparison.py
@ecomodeller, @daniel-caichac-DHI - maybe we set the default number of bins too many places? I think I got the remaining 4 now 🙄
> Default number of bins in scatter plot --- too many defaults?

- modelskill/model/_base.py
- modelskill/model/dfsu.py
- modelskill/model/factory.py
- modelskill/model/grid.py
- modelskill/model/point.py
- modelskill/model/track.py
> Model type hints

- modelskill/comparison/_collection.py
- modelskill/comparison/_comparison.py
- modelskill/comparison/_utils.py
- modelskill/skill.py
- notebooks/Multi_variable_comparison.ipynb
- tests/test_aggregated_skill.py
- tests/test_multivariable_compare.py
It is confusing to use both "variable" and "quantity". This PR renames all uses of variable to quantity. Also the properties var_names and n_variables are renamed.
> Rename variable to quantity

- modelskill/__init__.py
- tests/test_aggregated_skill.py
> SkillTable in root namespace

- .github/workflows/full_test.yml
- modelskill/comparison/_collection.py
*Note* that this PR wants to merge commits into the `groupby-sort-false` branch (not directly to `main`.
> Refactor long_dataframe

- modelskill/comparison/_comparison.py
- tests/test_comparer.py
attrs property is also needed on Comparer (just like recently implemented on Observation)
> Comparer attrs property

- .github/workflows/build_docs.yml
- docs/index.md
- docs/license.md
- mkdocs.yml
- pyproject.toml
> Docs landing page

- modelskill/metrics.py
> No need to use deprecated .ravel()

- modelskill/comparison/_collection.py
- tests/test_comparercollection.py
> Use deepcopy

- modelskill/comparison/_comparison.py
- pyproject.toml
- tests/test_comparer.py
With the consequence that `SkillTable.to_geodataframe()` lacks coordinates 😳
> Fix comparer wrong gtype

- modelskill/skill.py
NotImplemented and helpful message
> plot() should raise error if no default plot

- modelskill/matching.py
- tests/test_match.py
Closes #434 (see details there)
> Observation xyz is not included in Comparer for point-to-point comparisons

- .github/workflows/full_test.yml
- .github/workflows/scheduled_test.yml
- pyproject.toml
[netCDF4](https://pypi.org/project/netCDF4/1.7.2/) now since Oct 22 supports Python 3.13.
> Support for Python 3.13

- pyproject.toml
Ignore errors in metrics module.
> Use 3.10 syntax with mypy.

- modelskill/comparison/_comparison.py
- tests/test_match.py
> Preserve order of models from dataframe

- modelskill/comparison/_comparison.py
- modelskill/matching.py
- modelskill/model/point.py
- modelskill/model/track.py
- modelskill/obs.py
- modelskill/timeseries/_point.py
- tests/test_comparer.py
- tests/test_comparercollection.py
- uv.lock
*If adding type hints is challenging, the design is flawed*🙄
> Only call extract on model result types where it makes sense
