.github/workflows/full_test.yml, .github/workflows/scheduled_test.yml, setup.py, tests/test_modelresult.py
mikeio 0.7 have been released. This means that fmskill now runs on linux and python 3.9. We need to test this in our CI.
=> add linux tests

fmskill/comparison.py, fmskill/plot.py
Added the options of showing just a `sample` of scatter points (of 10k randomly selected points) or `N` number of points, also randomly selected.  A fixed random seed was hardcoded.
=> Show scatter points sample

fmskill/connection.py, tests/test_connector.py
```python
con = Connector(o1, [mr1[0], mr2[0]])
cc = con.extract()
con2 = Connector()
con2.add(o1, mr1[0])
con2.add(o1, mr2[0])
```
=> Adding models for the same observation after construction to Connector fails 

fmskill/comparison.py
Hi, I added an additional flag for scatter plots (point comparison only for the moment) that adds basic statistics table on the right side. Example:
* `comparer.scatter(model=modname,cmap='rainbow',
xlabel='Observation Hm0 [m]',
ylabel='Model Hm0 [m]',show_density=True,
)` gives the normal scatter
* adding the `skill_table=True` flag then makes it like this `comparer.scatter(model=modname,cmap='rainbow',
xlabel='Observation Hm0 [m]',
ylabel='Model Hm0 [m]',show_density=True,
skill_table=True)` 
Still to implement:
* Table flag for the spatial-skill scatter plot
*  Add dimensions (metres, seconds, etc.) as of right now fmskill does not take into account the physical unites (dimensions) of the comparisons
=> added skill table if requested

fmskill/comparison.py, fmskill/plot.py
Just a simple change in default scatter plots, I changed the default scatter plot from `2D Histogram` to `Points density`, so by default we would get:
`comparer.scatter(model=modname)`
Now 2D hist is not by default, so a kword show_hist must be included, then you get
`comparer.scatter(model=modname,show_hist=True)`
Also the number of points to be sampled for scatter plotting if the dataset is too large was increased from 10k to 50k.
No changes with respect to the default `cmap` yet
=> Default style

.github/workflows/full_test.yml, fmskill/comparison.py, fmskill/observation.py, fmskill/plot.py, tests/test_eum.py, tests/test_multimodelcompare.py, tests/test_multivariable_compare.py, tests/test_pointobservation.py, tests/test_trackobservation.py
Added an automatic units recognition from dfs0.item for singlepoint compare object scatter plot.
* If not dfs0 is provided (or if user wants to override units) a new kword `units=str` can be specified, for instance if instead of automatic units detection `units = °` user wanted to specify degrees north then flag `units = ' °N'` can be specified.  
* Also, shortening of the very basic units was added ( metres -> m; second - >s; degrees -> °, and; meter per second -> m/s). For any other unit (eg **cm/s**) the automatic detection will just write *'centimetres per second'* and it will be the user the one who should specify kword `units = 'cm/s'` . This could be improved in the future with a very long mapping dictionary of `long unit name -> short unit name`.
* Before this commit scatter plot …
=> added units flag scatter

fmskill/comparison.py, tests/test_pointobservation.py, tests/test_trackcompare.py
The purpose of the `SingleObsComparer.hist()` and the `ComparerCollection.hist()` should be to compare distributions. not counts. The number of observations can be wildly different from the number of modelled data, which makes comparing counts pretty useless.
=> Histogram default to density=True

fmskill/metrics.py, tests/test_multimodelcompare.py
=> Alternative implementation of the scatter index

fmskill/comparison.py, fmskill/plot.py
Hi,
I just did a very small change as before plotting a scatter with `skill_table` was only allowed for 1 observation vs the model.
Now it works for `n` number of observations with `n>=1` , and in this case the skill_table will be `cc.mean_skill()`
Example of skill table with 1 observation
---
Example of skill table with n>1 observations
---
This is a very powerful tool of fmskill (the `mean_skill`) and I changed nothing in it, just added the option to put it in a scatter plot.
=> Added Skill Table if N_obs>1

.gitignore, fmskill/__init__.py, fmskill/comparison.py, fmskill/plot.py, fmskill/settings.py, setup.py, tests/test_settings.py
fmskill.options with methods for:  
* registering fmskill options (including default value, decription and validator)
* referencing options using dot-notation
* restoring default values
=> package-wide options

fmskill/comparison.py, fmskill/plot.py
I am returning the axes object in scatter plot (just as is done in the timeseries) since sometimes people want to do things (ax.add_patches or ax.set_some_parameter or rename the ticks, etc) and it was not possible in the scatter plot.
In timeseries is done here
https://github.com/DHI/fmskill/blob/2c0f988c1c2ab2e3501e4b35b9a4ff5e34a0c435/fmskill/comparison.py#L1592-L1636
=> return AX in scatter

fmskill/__init__.py, fmskill/plot.py, fmskill/settings.py, fmskill/styles/mood.yml, fmskill/styles/simple.yml, tests/test_settings.py
Hi @jsmariegaard 
I ended up doing a new branch with mood style as per your suggestion. Much cleaner.
I think we can close the old branch: https://github.com/DHI/fmskill/pull/150
by default now you get this
and when style=MOOD
=> Mood Style

fmskill/plot.py
Hi, I added a warning the following reasons
* Usually when plotting a scatter plot with points, having 50k points is enough, and for larger datasets by default a sample of the dataset is plotted (as this is faster than plotting the complete dataset)
* In most cases this is ok, but sometimes the user wants to see all points to identify the possible outliers, this was already possible with `show_points=True` , but sometimes the user (aka myself) forget about this.
* I rarely have more than 50k points when comparing model/measurements, but when I do, I want to be reminded that the plot is just using a sample, so I added a warning that, if a sample of the total set is being plotted (despite the statistics being calculated on the total data set), will remind the user of this
* For smaller …
=> add warning scatter plot

docs/getting_started.rst
ModelResult no longer support multiple items
=> ModelResult - docs

fmskill/comparison.py, fmskill/observation.py, tests/test_comparer.py, tests/test_observation_track.py, tests/test_pointcompare.py
And data without a kind attribute are auxilliary variables.
=> Comparer further refactoring

fmskill/plot.py
Hi, two small changes
* First, I added one more bin on the Scatter plot on both edges, because before it was difficult to see the first/last quantiles plot. Actually since Xlim was = to max (x), the final point was cut in half. See fig. before/after.
Before
---
Now
---
* Second and last, the way the scatter density was being calculated was missing half a bin at both edges, which eliminated the extreme points (they were present in the QQ but not in the scatter). This only happened when `show_density=True`. If false, all points where there.
See before:
---
`show_density=True`
`show_density=False`
Now it shows all the points on the extremes.
See now
---
=> Style limits qq

fmskill/observation.py
Hi, i just added the mapping of `degree` to `°` to the short names function in the units (where `metre` is changed to `m` and seconds to `s` and `per` to `/` ), because degree is a long word an nobody wants to see
* Direction [degree]
but everyone likes
* Direction [°]
=> add degree to short names

fmskill/plot.py, tests/test_multivariable_compare.py
Hi, 
* I added an additional test for the scatter plot with density (actually extended a test by adding two lines, one with `bins=19` and another with `bins=21`)
* The reason behind this is that sometimes, as the way the 2d-histogram for scatter density plot was defined, given certain bin-sizes, the edges of the bins (2DHist bins) ended just before the center of the bins, which crashed the plots. This could easily be solved by changing the bin-size slightly or number of bins by one, but it is not ideal.
* So now, I check the last value of the center of the bins, and the last value of the edge of the bins, and if the latter is smaller than the former, I add an extra 1/2 bin, to make sure that the bin-edges fully cover the bins-center. This has no impact on the final result (plot), but …
=> fix small density-bug and added test

modelskill/comparison.py, modelskill/plot.py, tests/test_multimodelcompare.py, tests/test_plot.py
The `scatter()` function is one of the key functions of `modelskill` and needs to be understandable.
This PR aims to refactor this long function into several more manageable functions, and to highlight differences between the matplotlib version and the plotly version.
And remove deprecated arguments `binsize` and `nbins`.
=> Refactor `scatter()`

modelskill/comparison.py
A simple call to repr shouldn't issue warnings.
=> Don't issue warnings with no arguments

modelskill/comparison.py
Hi.
I just changed a single line. 
All tests still pass.
I am just changing metrics from a `numpy array` (so just values) to a pandas series. That way, the values are remain the same, but the time index is not lost.
This simple change allows me to calculate, for instance, the `Peak Ratio` metric, which requires `model data`, `measured data`, **and** time axis.
=> custom metrics as series

modelskill/comparison.py
When creating a point comparer object, the user can specify (if he wants) x,y,z, and by default they are none.
For some reason in the comparison objects, then the values of `x,y` where being inherited, (if None, `None` was being inherited) but `z` dissapeared, for no reason.
I just added `z` just like `x` and `y`
=> Added_z_comparison

modelskill/comparison.py, tests/test_comparer.py, tests/test_comparercollection.py
Fix issue occurring when adding ComparerCollections with altimetry data using new API
=> Fix add comparer track

modelskill/plot.py
Fixed issue related to warning: `No data for colormapping provided via 'c'. Parameters 'norm' will be ignored`
Added normalisation for coloured histogram (`show_hist`) parameter in  `.plot.scatter()` - will now behave similarly to `show_density`
=> Scatter vs histo density normalization

modelskill/comparison/_comparison.py, tests/test_multimodelcompare.py
We want to make the upgrade process as painless as possible, so this shouldn't have been removed. Thanks to @daniel-caichac-DHI for pointing this out.
=> Filtering in scatter is deprecated, not removed

modelskill/plot.py
Hi,
I just changed the legend for the time when the user specifies kword `fit_to_quantiles=True`, so it is explicit in the fit now. 
See example results.
Default:
QQ in the legend (also regression changes, of course):
=> fit_to_quantile legend

modelskill/metrics.py, notebooks/Metrics_widget.ipynb, pyproject.toml, tests/test_metrics.py
Hi,
I added 2 new metrics that will most likely be used in the validation services.
1: Explained Variation (EV). That on is straight forward. Formula added in docstring.
2: Peak Ratio (PR):
* For this one I need an ancilliary function called 'partial_duration_series', very similar to the PoT function from the EVA_editor in Mikezero toolbox (to identify peaks). 
* The peak ratio then is just the ratio of the mean of model peaks/ measured peaks.  
*  Added scipy to dependencies list
* Also added tests
=> new_metrics_validation_services

modelskill/metrics.py
Hi,
I added nothing new, but I realized that the `peak ratio` and `pr` metric had to be defined BEFORE this line
`defined_metrics: typing.Set[str] = (
set([func for func in dir() if callable(getattr(sys.modules[__name__], func))])
- NON_METRICS
)`
otherwise it does not store it as an available metric in the skill table. 
I just moved it before.
Please merge :)
=> moved Peak Ratio

modelskill/comparison/_collection_plotter.py, modelskill/comparison/_comparison.py, modelskill/metrics.py, tests/test_comparer.py, tests/test_multimodelcompare.py
Fix these two classes of warnings
* _FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]_
* _FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning._
=> Pandas deprecations

pyproject.toml
The code was removed previously but the executable script was still there, which I found out by accidently typing `modelskill` in my newly installed <https://ohmyz.sh/> which lets you type `$ some_folder` instead of  `$ cd some_folder` 🤓.
=> Remove entrypoint

.gitignore, modelskill/model/grid.py, modelskill/types.py, tests/model/test_grid.py, tests/test_comparer.py
If I don't care about the units (no quantity info added), I prefer to not have "Undefined" in the skill table.
This PR makes the skill table a bit cleaner 
And as bonus I throw in reading of conventional attributes [`long_name` and `units`](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03.html)
=> Unit handling

modelskill/metrics.py, tests/test_metrics.py
Ok, following @jsmariegaard  recommendation, I just did a simple PR exposing some kwargs in the Peak Ratio, and will try to use custom metrics instead.
=> Expose kwargs PR

modelskill/connection.py, tests/model/test_dfsu.py, tests/test_combine_comparers.py, tests/test_connector.py, tests/test_connector_conf.py, tests/test_pointcompare.py, tests/test_trackcompare.py
With the ambition to retire it completely in a future version.
=> Deprecate `Connector`

modelskill/comparison/_collection.py, modelskill/comparison/_comparison.py, tests/test_grid_skill.py
It is not possible to select nearest point or interp in a categorical index (categories are not sorted).
=> Change categorical index to float

modelskill/__init__.py, modelskill/observation.py, tests/observation/test_point_obs.py, tests/observation/test_track_obs.py, tests/test_match.py
A factory function for creating an appropriate observation object based on the data and args.
If 'x' or 'y' is given, a PointObservation is created.
If 'x_item' or 'y_item' is given, a TrackObservation is created.
>>> import modelskill as ms
>>> o_pt = ms.observation(df, item=0, x=366844, y=6154291, name="Klagshamn")
>>> o_tr = ms.observation("lon_after_lat.dfs0", item="wl", x_item=1, y_item=0)
Equivalent to `ms.model_result`
=> Observation factory function

modelskill/skill_grid.py, tests/test_grid_skill.py
To avoid selecting a model in plot
=> Skillgrid.sel

modelskill/comparison/_collection.py, modelskill/obs.py, modelskill/plotting/_misc.py, tests/test_comparercollection.py
=> Preserve comparer order on save/load

modelskill/metrics.py
Hi,
as discussed, if PR does not find any joint-peaks, instead of raising a value error we will be returning NaN as is done in other metrics.
=> PR when no joint peaks

mkdocs.yml
Still cannot manage to remove level 3 headings in right hand side TOC (e.g. "See Also") 🤯
This improvements are included: 
See also 
- https://github.com/tiangolo/fastapi/blob/master/docs/en/mkdocs.yml
- https://mkdocstrings.github.io/python/usage/
- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
=> Improved mkdocs.yml settings

modelskill/obs.py
By mistake the obs color (shown on timeseries plots) was chosen randomly in latest version (used to work fine)
=> Fix random obs colors

modelskill/comparison/_collection_plotter.py, modelskill/comparison/_comparer_plotter.py, modelskill/metrics.py, modelskill/plotting/_misc.py, modelskill/plotting/_scatter.py, tests/plot/test_plot.py
=> skill_table also for plotting.scatter

modelskill/comparison/_collection_plotter.py, modelskill/comparison/_comparer_plotter.py, modelskill/plotting/_misc.py, modelskill/plotting/_scatter.py
`skill_table` arg was previously silently ignored if the plotly backend was used in the scatter plot.
This PR introduces the possibility to quickly add a skill table to an interactive scatter plot as well.
=> Skill table in plotly scatter

modelskill/obs.py, tests/observation/test_point_obs.py
Easy access to the `data.attrs` dictionary.
=> Observation attrs

.github/workflows/full_test.yml, modelskill/comparison/_collection.py, modelskill/comparison/_collection_plotter.py, modelskill/comparison/_comparison.py, modelskill/comparison/_utils.py, modelskill/matching.py, modelskill/skill.py, modelskill/skill_grid.py, modelskill/timeseries/_timeseries.py, notebooks/Event-based_timeseries.ipynb, notebooks/Metocean_gridded_spatial_skill.ipynb, notebooks/Metocean_multi_model_comparison.ipynb, notebooks/Metocean_track_comparison.ipynb, notebooks/Metocean_track_comparison_global.ipynb, notebooks/Multi_variable_comparison.ipynb, notebooks/Prematched_with_auxiliary.ipynb, tests/model/test_point.py, tests/model/test_track.py, tests/observation/test_point_obs.py, tests/test_aggregated_skill.py, tests/test_comparer.py, tests/test_comparercollection.py, tests/test_grid_skill.py, tests/test_match.py, tests/test_multimodelcompare.py, tests/test_multivariable_compare.py, tests/test_pointcompare.py, tests/test_trackcompare.py
* groupby(..., sort=False) in skill() and similar methods
* correct tests accordingly
* Fix bug in weights when assigning from dict (caused wrong results in some cases)
* Re-introduce to_dataframe() on Comparer
* Syncronize to_dataframe() of Comparer and Timeseries such that they work in the same way (include aux also)
* Docstrings for all to_dataframe() methods
* Docstrings for several other methods
* Renaming of internal variables (and variables in tests) to confirm to best practice and for consistency (e.g. sk for skill() )
* New method sort_values() on SkillTable
* xy set to nan for skill() of track data
=> Don't sort on groupby (e.g. in skill() method)

modelskill/comparison/_collection.py, modelskill/comparison/_comparison.py, modelskill/comparison/_utils.py, tests/test_comparer.py
=> Long-dataframe with time column

modelskill/connection.py, modelskill/matching.py, modelskill/model/_base.py, modelskill/model/dfsu.py, modelskill/model/dummy.py, modelskill/model/grid.py, modelskill/model/point.py, modelskill/model/track.py, notebooks/Gridded_NetCDF_ModelResult.ipynb, tests/model/test_grid.py, tests/test_aggregated_skill.py, tests/test_config.py, tests/test_match.py, tests/test_multimodelcompare.py, tests/test_multivariable_compare.py, tests/test_pointcompare.py
Allow user to select spatial interp method when matching. 
Not sure what the new argument should be called 🤔. My first idea was `spatial_interp_method`, but it's long and when the choice is "contained" it doesn't seem like a good name. Maybe `spatial_method` is better? Or `spatial_matching`? 
Choosing good default is not easy. 😬
Before this PR the defaults were:
* Dfsu: nearest point for track; contained for point
* Grid: linear for track; nearest for point. 
We need to clean this up before the release! 
Proposed new spatial interpolation defaults:
* Dfsu: inverse_distance for both point and track (both will be linear in time).
* Grid: linear for both point and track.
Some problems/considerations:
* Dfsu: option "contained" is only supported for point, not track
* Dfsu: in MIKE IO the …
=> Spatial interp method

modelskill/utils.py
```bash
$ ruff --preview --select NPY201
modelskill/utils.py:144:27: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
Found 1 error.
[*] 1 fixable with the `--fix` option.
```
Seems like we are well prepared for this upcoming release.
_The tentative release date for the first release candidate of NumPy 2.0 is around 1 Feb 2024, and the final release 6-8 weeks later._ <https://github.com/numpy/numpy/issues/24300>
=> Prepare for NumPy 2

modelskill/metrics.py, tests/test_comparercollection.py, tests/test_metrics.py
Hi.
After a **long** discussion we decided to update the peak selection in the Peak Ratio.
* Before this PullRequest the individual N-largests peaks between model and measurements were selected and then intersected (ie, finding the joint-events only), and the remaining joint-peaks were used in the calculation.
* With this PullRequest , all individual peaks are selected independently (from measurements and model), intersected (finding the joint-events), and then the N-largest peaks are used for the calculation.
Small change but has some implications in the results. Also the number of times the user gets a NaN (no joint events) is much lower now (still can happen with very short time series with no evident peaks).
I had to obviously update the tests results of PR as the expected values now …
=> New Peak Ratio

Makefile, modelskill/matching.py, tests/test_match.py
=> Check order of args in match

modelskill/skill.py
Previously, by default, the x positions of the skill plots were at [1, 2, 3, ..., n]. However, when an aux variable is numeric, that raised rendering issues (see issue #429). 
This PR changes the handling of x labels in skill plots based on whether the x values are numeric or not.
=> Fixing issue with x axis label

.devcontainer/devcontainer.json, .github/workflows/full_test.yml, .vscode/settings.json, CONTRIBUTING.md, Makefile, modelskill/comparison/__init__.py, modelskill/comparison/_comparison.py, modelskill/matching.py, modelskill/metrics.py, modelskill/model/_base.py, modelskill/model/dfsu.py, modelskill/model/grid.py, modelskill/model/point.py, modelskill/settings.py, modelskill/skill.py, modelskill/skill_grid.py, modelskill/timeseries/_timeseries.py, pyproject.toml
=> Use ruff for formatting instead of black

.vscode/settings.json
Only selected people are allowed to push to `main`, but it is helpful to get a warning first, a bit to easy to sync by accident in VS Code.
=> Branch protection

modelskill/comparison/_comparer_plotter.py, pyproject.toml
https://docs.astral.sh/ruff/configuration/#configuring-ruff
=> Add missing ruff lint default rules

modelskill/matching.py, tests/test_match.py
1. Observation and model aux variables are not allowed to have identical names. This has to be explicit
2. Aux variables from model can be identical, they are likely to be identical. (Last one will win).
=> Aux overlapping name logic

modelskill/metrics.py
I found a bug in the Peak Ratio, so rare that almost never shows up, but in case where the peaks are VERY small (as in, <<1) it could show up.
The top N peaks must be selected as the `minimum` between the `Average Annual  Peaks` * `Number of years` (so eg in 40 years with AAP 2  = 80 peaks) and the total number of peaks (`len(peaks)`)
I was doing a `np.sum(peaks)` of the peaks, ie, adding the Peak Values.
This is clearly wrong. I should either have done `np.sum(peak_index)` since `peak index` is an array of booleans , or simply, just count the total number of peaks (`len(peaks)`), as was done in this PR
=> pr bug fix
